---
#- import_tasks: osp-repos.yml

  - name: Install all the required rpms (this will take a while)
    yum:
      name: "{{ req_rpm }}"
      state: latest

      #  - name: set hostname
      #hostname:
      #name: "{{ undercloud['hostname'] }}"

      #- name: add line to /etc/hosts as required
      #lineinfile:
      #dest: /etc/hosts
      #state: present
      #regexp: '^{{ external_ip }}'
      #line: '{{ external_ip }} {{ fqdn }} {{ fqdn_short }}'

      #  - name: change to ipv4 forward
      #systctl:
      #name: net.ipv4.ip_forward
      #value: 1
      #sysctl_set: yes
      #state: present
      #reload: yes

  - name: start mariadb
    systemd:
      name: mariadb
      state: started

  - name:  turn off requiretty for sudo
    lineinfile:
      dest: /etc/sudoers
      line: "{{ item.line }}"
      state: "{{ item.state }}"
    with_items:
      - { line: "Defaults !requiretty", state: present }
      - { line: "Defaults requiretty", state: absent }

  - name: check sudoers
    shell: cat /etc/sudoers | grep tty
    register: sudoers_output

  - name: Create the group stack
    group:
      name: "{{ stack_group }}"
      state: present

  - name: Create the user stack
    user:
      name: "{{ stack_user }}"
      group: "{{ stack_group }}"
      password: "{{ stack_passwd }}" #can use vault

  - name: Create the required directories
    file:
      state: directory
      name: "{{ item }}"
      group: "{{ stack_group }}"
    with_items:
      - /home/stack/images/
      - /home/stack/templates/

  - name: Create the stack file for sudoers
    copy:
      src: stack
      dest: /etc/sudoers.d/
      mode: "{{ sudoer_perm }}"

  - name: copy the undercloud file
    copy:
      src: undercloud.conf
      dest: /home/stack/undercloud.conf
      mode: "{{ sudoer_perm }}"
      group: "{{ stack_group }}"
      owner: "{{ stack_user }}"

    #- name: Copy over the undercloud file
    #template:
    #src: undercloud.conf.j2
    #dest: /home/stack/undercloud.conf
    #mode: "{{ sudoer_perm }}"
    #group: "{{ stack_group }}"
    #owner: "{{ stack_user }}"

  - name: Install the undercloud
    become: yes
    become_user: stack
    command: "openstack undercloud install"
    register: undercloud_install
    args:
      chdir: /home/stack/
    async: 2700
    poll: 30
    changed_when: False

  - name: Check openstack catalog list
    shell: openstack catalog list >> catalog.txt

  - name: Verify neutron
    shell: neutron net-list

  - name: Verify neutron 2
    shell: neutron subnet-list
